# Generated by Django 3.2.9 on 2021-11-03 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='帳號序號')),
                ('real_name', models.CharField(blank=True, max_length=30, verbose_name='真實姓名')),
                ('gender', models.IntegerField(blank=True, default=0, verbose_name='姓別')),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帳號名稱')),
            ],
        ),
    ]
